include(macros.cmake)
cmake_minimum_required(VERSION 3.10)
set(CMAKE_MESSAGE_LOG_LEVEL VERBOSE)
project(QtChess CXX)
file(GLOB ALL_FILES *.cpp *.hpp)
configureQMOC()
add_executable(${PROJECT_NAME} ${ALL_FILES})
find_package(Qt5 COMPONENTS Core Widgets REQUIRED)
target_link_libraries(${PROJECT_NAME} Qt5::Core Qt5::Widgets)
target_include_directories(${PROJECT_NAME} SYSTEM PRIVATE "include")